-  hosts: localhost
   gather_facts: False
   vars:
     hostname: nginx
     keypair: my_key1
     instance_type: t2.micro
     security_group: EC2SecurityGroup
     image: ami-085925f297f89fce1
     region: us-east-1 
   tasks:
    - name: Launch instance
      ec2:
         key_name: "{{ keypair }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         region: "{{ region }}"
         count: 1 
         wait: true
         user_data: |
                    #!/bin/sh
                    sudo apt-get install nginx -y
      register: ec2
